package core;

public class Names 
{
	static String[] pokemonNames = 
		{
			"Abra",
			"Aerodactyl",
			"Alakazam",
			"Arbok",
			"Arcanine",
			"Articuno",
			"Beedrill",
			"Bellsprout",
			"Blastoise",
			"Bulbasaur",
			"Butterfree",
			"Caterpie",
			"Chansey",
			"Charizard",
			"Charmander",
			"Charmeleon",
			"Clefable",
			"Clefairy",
			"Cloyster",
			"Cubone",
			"Dewgong",
			"Diglett",
			"Ditto",
			"Dodrio",
			"Doduo",
			"Dragonair",
			"Dragonite",
			"Dratini",
			"Drowzee",
			"Dugtrio",
			"Eevee",
			"Ekans",
			"Electabuzz",
			"Electrode",
			"Exeggcute",
			"Exeggutor",
			"Farfetch'd",
			"Fearow",
			"Flareon",
			"Gastly",
			"Gengar",
			"Geodude",
			"Gloom",
			"Golbat",
			"Goldeen",
			"Golduck",
			"Golem",
			"Graveler",
			"Grimer",
			"Growlithe",
			"Gyarados",
			"Haunter",
			"Hitmonchan",
			"Hitmonlee",
			"Horsea",
			"Hypno",
			"Ivysaur",
			"Jigglypuff",
			"Jolteon",
			"Jynx",
			"Kabuto",
			"Kabutops",
			"Kadabra",
			"Kakuna",
			"Kangaskhan",
			"Kingler",
			"Koffing",
			"Krabby",
			"Lapras",
			"Lickitung",
			"Machamp",
			"Machoke",
			"Machop",
			"Magikarp",
			"Magmar",
			"Magnemite",
			"Magneton",
			"Mankey",
			"Marowak",
			"Meowth",
			"Metapod",
			"Mew",
			"Mewtwo",
			"Moltres",
			"Mr. Mime",
			"Muk",
			"Nidoking",
			"Nidoqueen",
			"NidoranFemale",
			"NidoranMale",
			"Nidorina",
			"Nidorino",
			"Ninetales",
			"Oddish",
			"Omanyte",
			"Omastar",
			"Onix",
			"Paras",
			"Parasect",
			"Persian",
			"Pidgeot",
			"Pidgeotto",
			"Pidgey",
			"Pikachu",
			"Pinsir",
			"Poliwag",
			"Poliwhirl",
			"Poliwrath",
			"Ponyta",
			"Porygon",
			"Primeape",
			"Psyduck",
			"Raichu",
			"Rapidash",
			"Rattata",
			"Raticate",
			"Rhydon",
			"Rhyhorn",
			"Sandshrew",
			"Sandslash",
			"Scyther",
			"Seadra",
			"Seaking",
			"Seel",
			"Shellder",
			"Slowbro",
			"Slowpoke",
			"Snorlax",
			"Spearow",
			"Squirtle",
			"Starmie",
			"Staryu",
			"Tangela",
			"Tauros",
			"Tentacool",
			"Tentacruel",
			"Vaporeon",
			"Venomoth",
			"Venonat",
			"Venusaur",
			"Victreebel",
			"Vileplume",
			"Voltorb",
			"Vulpix",
			"Wartortle",
			"Weedle",
			"Weepinbell",
			"Weezing",
			"Wigglytuff",
			"Zapdos",
			"Zubat"
		};

	static String[] natureNames = 
		{
			"Hardy",
			"Lonely",
			"Brave",
			"Adamant",
			"Naughty",
			"Bold",
			"Docile",
			"Relaxed",
			"Impish",
			"Lax",
			"Timid",
			"Hasty",
			"Serious",
			"Jolly",
			"Naive",
			"Modest",
			"Mild",
			"Quiet",
			"Bashful",
			"Rash",
			"Calm",
			"Gentle",
			"Sassy",
			"Careful",
			"Quirky"
		};
	public enum moveNames 
	{
		NONE,
		TEN_MILLION_VOLT_THUNDERBOLT,
		ABSORB,
		ACCELEROCK,
		ACID,
		ACID_ARMOR,
		ACID_DOWNPOUR_P,
		ACID_DOWNPOUR_S,
		ACID_SPRAY,
		ACROBATICS,
		ACUPRESSURE,
		AERIAL_ACE,
		AEROBLAST,
		AFTER_YOU,
		AGILITY,
		AIR_CUTTER,
		AIR_SLASH,
		ALL_OUT_PUMMELING_P,
		ALL_OUT_PUMMELING_S,
		ALLY_SWITCH,
		AMNESIA,
		ANCHOR_SHOT,
		ANCIENT_POWER,
		AQUA_JET,
		AQUA_RING,
		AQUA_TAIL,
		ARM_THRUST,
		AROMATHERAPY,
		AROMATIC_MIST,
		ASSIST,
		ASSURANCE,
		ASTONISH,
		ATTACK_ORDER,
		ATTRACT,
		AURA_SPHERE,
		AURORA_BEAM,
		AURORA_VEIL,
		AUTOTOMIZE,
		AVALANCHE,
		BABY_DOLL_EYES,
		BANEFUL_BUNKER,
		BARRAGE,
		BARRIER,
		BATON_PASS,
		BEAK_BLAST,
		BEAT_UP,
		BELCH,
		BELLY_DRUM,
		BESTOW,
		BIDE,
		BIND,
		BITE,
		BLACK_HOLE_ECLIPSE_P,
		BLACK_HOLE_ECLIPSE_S,
		BLAST_BURN,
		BLAZE_KICK,
		BLIZZARD,
		BLOCK,
		BLOOM_DOOM_P,
		BLOOM_DOOM_S,
		BLUE_FLARE,
		BODY_SLAM,
		BOLT_STRIKE,
		BONE_CLUB,
		BONE_RUSH,
		BONEMERANG,
		BOOMBURST,
		BOUNCE,
		BRAVE_BIRD,
		BREAKNECK_BLITZ_P,
		BREAKNECK_BLITZ_S,
		BRICK_BREAK,
		BRINE,
		BRUTAL_SWING,
		BUBBLE_BEAM,
		BUBBLE,
		BUG_BITE,
		BUG_BUZZ,
		BULK_UP,
		BULLDOZE,
		BULLET_PUNCH,
		BULLET_SEED,
		BURN_UP,
		CALM_MIND,
		CAMOUFLAGE,
		CAPTIVATE,
		CATASTROPIKA,
		CELEBRATE,
		CHARGE_BEAM,
		CHARGE,
		CHARM,
		CHATTER,
		CHIP_AWAY,
		CIRCLE_THROW,
		CLAMP,
		CLANGING_SCALES,
		CLEAR_SMOG,
		CLOSE_COMBAT,
		COIL,
		COMET_PUNCH,
		CONFIDE,
		CONFUSE_RAY,
		CONFUSION,
		CONSTRICT,
		CONTINENTAL_CRUSH_P,
		CONTINENTAL_CRUSH_S,
		CONVERSION_2,
		CONVERSION,
		COPYCAT,
		CORE_ENFORCER,
		CORKSCREW_CRASH_P,
		CORKSCREW_CRASH_S,
		COSMIC_POWER,
		COTTON_GUARD,
		COTTON_SPORE,
		COUNTER,
		COVET,
		CRABHAMMER,
		CRAFTY_SHIELD,
		CROSS_CHOP,
		CROSS_POISON,
		CRUNCH,
		CRUSH_CLAW,
		CRUSH_GRIP,
		CURSE,
		CUT,
		DARK_PULSE,
		DARK_VOID,
		DARKEST_LARIAT,
		DAZZLING_GLEAM,
		DEFEND_ORDER,
		DEFENSE_CURL,
		DEFOG,
		DESTINY_BOND,
		DETECT,
		DEVASTATING_DRAKE_P,
		DEVASTATING_DRAKE_S,
		DIAMOND_STORM,
		DIG,
		DISABLE,
		DISARMING_VOICE,
		DISCHARGE,
		DIVE,
		DIZZY_PUNCH,
		DOOM_DESIRE,
		DOUBLE_HIT,
		DOUBLE_KICK,
		DOUBLE_SLAP,
		DOUBLE_TEAM,
		DOUBLE_EDGE,
		DRACO_METEOR,
		DRAGON_ASCENT,
		DRAGON_BREATH,
		DRAGON_CLAW,
		DRAGON_DANCE,
		DRAGON_HAMMER,
		DRAGON_PULSE,
		DRAGON_RAGE,
		DRAGON_RUSH,
		DRAGON_TAIL,
		DRAIN_PUNCH,
		DRAINING_KISS,
		DREAM_EATER,
		DRILL_PECK,
		DRILL_RUN,
		DUAL_CHOP,
		DYNAMIC_PUNCH,
		EARTH_POWER,
		EARTHQUAKE,
		ECHOED_VOICE,
		EERIE_IMPULSE,
		EGG_BOMB,
		ELECTRIC_TERRAIN,
		ELECTRIFY,
		ELECTRO_BALL,
		ELECTROWEB,
		EMBARGO,
		EMBER,
		ENCORE,
		ENDEAVOR,
		ENDURE,
		ENERGY_BALL,
		ENTRAINMENT,
		ERUPTION,
		EXPLOSION,
		EXTRASENSORY,
		EXTREME_EVOBOOST,
		EXTREME_SPEED,
		FACADE,
		FAIRY_LOCK,
		FAIRY_WIND,
		FAKE_OUT,
		FAKE_TEARS,
		FALSE_SWIPE,
		FEATHER_DANCE,
		FEINT_ATTACK,
		FEINT,
		FELL_STINGER,
		FIERY_DANCE,
		FINAL_GAMBIT,
		FIRE_BLAST,
		FIRE_FANG,
		FIRE_LASH,
		FIRE_PLEDGE,
		FIRE_PUNCH,
		FIRE_SPIN,
		FIRST_IMPRESSION,
		FISSURE,
		FLAIL,
		FLAME_BURST,
		FLAME_CHARGE,
		FLAME_WHEEL,
		FLAMETHROWER,
		FLARE_BLITZ,
		FLASH_CANNON,
		FLASH,
		FLATTER,
		FLEUR_CANNON,
		FLING,
		FLORAL_HEALING,
		FLOWER_SHIELD,
		FLY,
		FLYING_PRESS,
		FOCUS_BLAST,
		FOCUS_ENERGY,
		FOCUS_PUNCH,
		FOLLOW_ME,
		FORCE_PALM,
		FORESIGHT,
		FORESTS_CURSE,
		FOUL_PLAY,
		FREEZE_SHOCK,
		FREEZE_DRY,
		FRENZY_PLANT,
		FROST_BREATH,
		FRUSTRATION,
		FURY_ATTACK,
		FURY_CUTTER,
		FURY_SWIPES,
		FUSION_BOLT,
		FUSION_FLARE,
		FUTURE_SIGHT,
		GASTRO_ACID,
		GEAR_GRIND,
		GEAR_UP,
		GENESIS_SUPERNOVA,
		GEOMANCY,
		GIGA_DRAIN,
		GIGA_IMPACT,
		GIGAVOLT_HAVOC_P,
		GIGAVOLT_HAVOC_S,
		GLACIATE,
		GLARE,
		GRASS_KNOT,
		GRASS_PLEDGE,
		GRASS_WHISTLE,
		GRASSY_TERRAIN,
		GRAVITY,
		GROWL,
		GROWTH,
		GRUDGE,
		GUARD_SPLIT,
		GUARD_SWAP,
		GUARDIAN_OF_ALOLA,
		GUILLOTINE,
		GUNK_SHOT,
		GUST,
		GYRO_BALL,
		HAIL,
		HAMMER_ARM,
		HAPPY_HOUR,
		HARDEN,
		HAZE,
		HEAD_CHARGE,
		HEAD_SMASH,
		HEADBUTT,
		HEAL_BELL,
		HEAL_BLOCK,
		HEAL_ORDER,
		HEAL_PULSE,
		HEALING_WISH,
		HEART_STAMP,
		HEART_SWAP,
		HEAT_CRASH,
		HEAT_WAVE,
		HEAVY_SLAM,
		HELPING_HAND,
		HEX,
		HIDDEN_POWER,
		HIGH_HORSEPOWER,
		HIGH_JUMP_KICK,
		HOLD_BACK,
		HOLD_HANDS,
		HONE_CLAWS,
		HORN_ATTACK,
		HORN_DRILL,
		HORN_LEECH,
		HOWL,
		HURRICANE,
		HYDRO_CANNON,
		HYDRO_PUMP,
		HYDRO_VORTEX_P,
		HYDRO_VORTEX_S,
		HYPER_BEAM,
		HYPER_FANG,
		HYPER_VOICE,
		HYPERSPACE_FURY,
		HYPERSPACE_HOLE,
		HYPNOSIS,
		ICE_BALL,
		ICE_BEAM,
		ICE_BURN,
		ICE_FANG,
		ICE_HAMMER,
		ICE_PUNCH,
		ICE_SHARD,
		ICICLE_CRASH,
		ICICLE_SPEAR,
		ICY_WIND,
		IMPRISON,
		INCINERATE,
		INFERNO_OVERDRIVE_P,
		INFERNO_OVERDRIVE_S,
		INFERNO,
		INFESTATION,
		INGRAIN,
		INSTRUCT,
		ION_DELUGE,
		IRON_DEFENSE,
		IRON_HEAD,
		IRON_TAIL,
		JUDGMENT,
		JUMP_KICK,
		KARATE_CHOP,
		KINESIS,
		KINGS_SHIELD,
		KNOCK_OFF,
		LANDS_WRATH,
		LASER_FOCUS,
		LAST_RESORT,
		LAVA_PLUME,
		LEAF_BLADE,
		LEAF_STORM,
		LEAF_TORNADO,
		LEAFAGE,
		LEECH_LIFE,
		LEECH_SEED,
		LEER,
		LICK,
		LIGHT_OF_RUIN,
		LIGHT_SCREEN,
		LIQUIDATION,
		LOCK_ON,
		LOVELY_KISS,
		LOW_KICK,
		LOW_SWEEP,
		LUCKY_CHANT,
		LUNAR_DANCE,
		LUNGE,
		LUSTER_PURGE,
		MACH_PUNCH,
		MAGIC_COAT,
		MAGIC_ROOM,
		MAGICAL_LEAF,
		MAGMA_STORM,
		MAGNET_BOMB,
		MAGNET_RISE,
		MAGNETIC_FLUX,
		MAGNITUDE,
		MALICIOUS_MOONSAULT,
		MAT_BLOCK,
		ME_FIRST,
		MEAN_LOOK,
		MEDITATE,
		MEGA_DRAIN,
		MEGA_KICK,
		MEGA_PUNCH,
		MEGAHORN,
		MEMENTO,
		METAL_BURST,
		METAL_CLAW,
		METAL_SOUND,
		METEOR_MASH,
		METRONOME,
		MILK_DRINK,
		MIMIC,
		MIND_READER,
		MINIMIZE,
		MIRACLE_EYE,
		MIRROR_COAT,
		MIRROR_MOVE,
		MIRROR_SHOT,
		MIST_BALL,
		MIST,
		MISTY_TERRAIN,
		MOONBLAST,
		MOONGEIST_BEAM,
		MOONLIGHT,
		MORNING_SUN,
		MUD_BOMB,
		MUD_SHOT,
		MUD_SPORT,
		MUDDY_WATER,
		MUD_SLAP,
		MULTI_ATTACK,
		MYSTICAL_FIRE,
		NASTY_PLOT,
		NATURAL_GIFT,
		NATURE_POWER,
		NATURES_MADNESS,
		NEEDLE_ARM,
		NEVER_ENDING_NIGHTMARE_P,
		NEVER_ENDING_NIGHTMARE_S,
		NIGHT_DAZE,
		NIGHT_SHADE,
		NIGHT_SLASH,
		NIGHTMARE,
		NOBLE_ROAR,
		NUZZLE,
		OBLIVION_WING,
		OCEANIC_OPERETTA,
		OCTAZOOKA,
		ODOR_SLEUTH,
		OMINOUS_WIND,
		ORIGIN_PULSE,
		OUTRAGE,
		OVERHEAT,
		PAIN_SPLIT,
		PARABOLIC_CHARGE,
		PARTING_SHOT,
		PAY_DAY,
		PAYBACK,
		PECK,
		PERISH_SONG,
		PETAL_BLIZZARD,
		PETAL_DANCE,
		PHANTOM_FORCE,
		PIN_MISSILE,
		PLAY_NICE,
		PLAY_ROUGH,
		PLUCK,
		POISON_FANG,
		POISON_GAS,
		POISON_JAB,
		POISON_POWDER,
		POISON_STING,
		POISON_TAIL,
		POLLEN_PUFF,
		POUND,
		POWDER_SNOW,
		POWDER,
		POWER_GEM,
		POWER_SPLIT,
		POWER_SWAP,
		POWER_TRICK,
		POWER_TRIP,
		POWER_WHIP,
		POWER_UP_PUNCH,
		PRECIPICE_BLADES,
		PRESENT,
		PRISMATIC_LASER,
		PROTECT,
		PSYBEAM,
		PSYCH_UP,
		PSYCHIC_FANGS,
		PSYCHIC_TERRAIN,
		PSYCHIC,
		PSYCHO_BOOST,
		PSYCHO_CUT,
		PSYCHO_SHIFT,
		PSYSHOCK,
		PSYSTRIKE,
		PSYWAVE,
		PULVERIZING_PANCAKE,
		PUNISHMENT,
		PURIFY,
		PURSUIT,
		QUASH,
		QUICK_ATTACK,
		QUICK_GUARD,
		QUIVER_DANCE,
		RAGE_POWDER,
		RAGE,
		RAIN_DANCE,
		RAPID_SPIN,
		RAZOR_LEAF,
		RAZOR_SHELL,
		RAZOR_WIND,
		RECOVER,
		RECYCLE,
		REFLECT_TYPE,
		REFLECT,
		REFRESH,
		RELIC_SONG,
		REST,
		RETALIATE,
		RETURN,
		REVELATION_DANCE,
		REVENGE,
		REVERSAL,
		ROAR_OF_TIME,
		ROAR,
		ROCK_BLAST,
		ROCK_CLIMB,
		ROCK_POLISH,
		ROCK_SLIDE,
		ROCK_SMASH,
		ROCK_THROW,
		ROCK_TOMB,
		ROCK_WRECKER,
		ROLE_PLAY,
		ROLLING_KICK,
		ROLLOUT,
		ROOST,
		ROTOTILLER,
		ROUND,
		SACRED_FIRE,
		SACRED_SWORD,
		SAFEGUARD,
		SAND_ATTACK,
		SAND_TOMB,
		SANDSTORM,
		SAVAGE_SPIN_OUT_P,
		SAVAGE_SPIN_OUT_S,
		SCALD,
		SCARY_FACE,
		SCRATCH,
		SCREECH,
		SEARING_SHOT,
		SECRET_POWER,
		SECRET_SWORD,
		SEED_BOMB,
		SEED_FLARE,
		SEISMIC_TOSS,
		SELF_DESTRUCT,
		SHADOW_BALL,
		SHADOW_BONE,
		SHADOW_CLAW,
		SHADOW_FORCE,
		SHADOW_PUNCH,
		SHADOW_SNEAK,
		SHARPEN,
		SHATTERED_PSYCHE_P,
		SHATTERED_PSYCHE_S,
		SHEER_COLD,
		SHELL_SMASH,
		SHELL_TRAP,
		SHIFT_GEAR,
		SHOCK_WAVE,
		SHORE_UP,
		SIGNAL_BEAM,
		SILVER_WIND,
		SIMPLE_BEAM,
		SING,
		SINISTER_ARROW_RAID,
		SKETCH,
		SKILL_SWAP,
		SKULL_BASH,
		SKY_ATTACK,
		SKY_DROP,
		SKY_UPPERCUT,
		SLACK_OFF,
		SLAM,
		SLASH,
		SLEEP_POWDER,
		SLEEP_TALK,
		SLUDGE_BOMB,
		SLUDGE_WAVE,
		SLUDGE,
		SMACK_DOWN,
		SMART_STRIKE,
		SMELLING_SALTS,
		SMOG,
		SMOKESCREEN,
		SNARL,
		SNATCH,
		SNORE,
		SOAK,
		SOFT_BOILED,
		SOLAR_BEAM,
		SOLAR_BLADE,
		SONIC_BOOM,
		SOUL_STEALING_7_STAR_STRIKE,
		SPACIAL_REND,
		SPARK,
		SPARKLING_ARIA,
		SPECTRAL_THIEF,
		SPEED_SWAP,
		SPIDER_WEB,
		SPIKE_CANNON,
		SPIKES,
		SPIKY_SHIELD,
		SPIRIT_SHACKLE,
		SPIT_UP,
		SPITE,
		SPLASH,
		SPORE,
		SPOTLIGHT,
		STEALTH_ROCK,
		STEAM_ERUPTION,
		STEAMROLLER,
		STEEL_WING,
		STICKY_WEB,
		STOCKPILE,
		STOKED_SPARKSURFER,
		STOMP,
		STOMPING_TANTRUM,
		STONE_EDGE,
		STORED_POWER,
		STORM_THROW,
		STRENGTH_SAP,
		STRENGTH,
		STRING_SHOT,
		STRUGGLE_BUG,
		STRUGGLE,
		STUN_SPORE,
		SUBMISSION,
		SUBSTITUTE,
		SUBZERO_SLAMMER_P,
		SUBZERO_SLAMMER_S,
		SUCKER_PUNCH,
		SUNNY_DAY,
		SUNSTEEL_STRIKE,
		SUPER_FANG,
		SUPERPOWER,
		SUPERSONIC_SKYSTRIKE_P,
		SUPERSONIC_SKYSTRIKE_S,
		SUPERSONIC,
		SURF,
		SWAGGER,
		SWALLOW,
		SWEET_KISS,
		SWEET_SCENT,
		SWIFT,
		SWITCHEROO,
		SWORDS_DANCE,
		SYNCHRONOISE,
		SYNTHESIS,
		TACKLE,
		TAIL_GLOW,
		TAIL_SLAP,
		TAIL_WHIP,
		TAILWIND,
		TAKE_DOWN,
		TAUNT,
		TEARFUL_LOOK,
		TECHNO_BLAST,
		TECTONIC_RAGE_P,
		TECTONIC_RAGE_S,
		TEETER_DANCE,
		TELEKINESIS,
		TELEPORT,
		THIEF,
		THOUSAND_ARROWS,
		THOUSAND_WAVES,
		THRASH,
		THROAT_CHOP,
		THUNDER_FANG,
		THUNDER_PUNCH,
		THUNDER_SHOCK,
		THUNDER_WAVE,
		THUNDER,
		THUNDERBOLT,
		TICKLE,
		TOPSY_TURVY,
		TORMENT,
		TOXIC_SPIKES,
		TOXIC_THREAD,
		TOXIC,
		TRANSFORM,
		TRI_ATTACK,
		TRICK_ROOM,
		TRICK,
		TRICK_OR_TREAT,
		TRIPLE_KICK,
		TROP_KICK,
		TRUMP_CARD,
		TWINEEDLE,
		TWINKLE_TACKLE_P,
		TWINKLE_TACKLE_S,
		TWISTER,
		UPROAR,
		U_TURN,
		VACUUM_WAVE,
		V_CREATE,
		VENOM_DRENCH,
		VENOSHOCK,
		VICE_GRIP,
		VINE_WHIP,
		VITAL_THROW,
		VOLT_SWITCH,
		VOLT_TACKLE,
		WAKE_UP_SLAP,
		WATER_GUN,
		WATER_PLEDGE,
		WATER_PULSE,
		WATER_SHURIKEN,
		WATER_SPORT,
		WATER_SPOUT,
		WATERFALL,
		WEATHER_BALL,
		WHIRLPOOL,
		WHIRLWIND,
		WIDE_GUARD,
		WILD_CHARGE,
		WILL_O_WISP,
		WING_ATTACK,
		WISH,
		WITHDRAW,
		WONDER_ROOM,
		WOOD_HAMMER,
		WORK_UP,
		WORRY_SEED,
		WRAP,
		WRING_OUT,
		X_SCISSOR,
		YAWN,
		ZAP_CANNON,
		ZEN_HEADBUTT,
		ZING_ZAP
	}
	public static String[] fullMoveNames =
		{
			/*0*/ 	"None",
			/*1*/	"10,000,000 Volt Thunderbolt",
			/*2*/	"Absorb",
			/*3*/	"Accelerock",
			/*4*/	"Acid",
			/*5*/	"Acid Armor",
			/*6*/	"Acid Downpour",
			/*7*/	"Acid Downpour",
			/*8*/	"Acid Spray",
			/*9*/	"Acrobatics",
			/*10*/	"Acupressure",
			/*11*/	"Aerial Ace",
			/*12*/	"Aeroblast",
			/*13*/	"After You",
			/*14*/	"Agility",
			/*15*/	"Air Cutter",
			/*16*/	"Air Slash",
			/*17*/	"All-Out Pummeling",
			/*18*/	"All-Out Pummeling",
			/*19*/	"Ally Switch",
			/*20*/	"Amnesia",
			/*21*/	"Anchor Shot",
			/*22*/	"Ancient Power",
			/*23*/	"Aqua Jet",
			/*24*/	"Aqua Ring",
			/*25*/	"Aqua Tail",
			/*26*/	"Arm Thrust",
			/*27*/	"Aromatherapy",
			/*28*/	"Aromatic Mist",
			/*29*/	"Assist",
			/*30*/	"Assurance",
			/*31*/	"Astonish",
			/*32*/	"Attack Order",
			/*33*/	"Attract",
			/*34*/	"Aura Sphere",
			/*35*/	"Aurora Beam",
			/*36*/	"Aurora Veil",
			/*37*/	"Autotomize",
			/*38*/	"Avalanche",
			/*39*/	"Baby-Doll Eyes",
			/*40*/	"Baneful Bunker",
			/*41*/	"Barrage",
			/*42*/	"Barrier",
			/*43*/	"Baton Pass",
			/*44*/	"Beak Blast",
			/*45*/	"Beat Up",
			/*46*/	"Belch",
			/*47*/	"Belly Drum",
			/*48*/	"Bestow",
			/*49*/	"Bide",
			/*50*/	"Bind",
			/*51*/	"Bite",
			/*52*/	"Black Hole Eclipse",
			/*53*/	"Black Hole Eclipse",
			/*54*/	"Blast Burn",
			/*55*/	"Blaze Kick",
			/*56*/	"Blizzard",
			/*57*/	"Block",
			/*58*/	"Bloom Doom",
			/*59*/	"Bloom Doom",
			/*60*/	"Blue Flare",
			/*61*/	"Body Slam",
			/*62*/	"Bolt Strike",
			/*63*/	"Bone Club",
			/*64*/	"Bone Rush",
			/*65*/	"Bonemerang",
			/*66*/	"Boomburst",
			/*67*/	"Bounce",
			/*68*/	"Brave Bird",
			/*69*/	"Breakneck Blitz",
			/*70*/	"Breakneck Blitz",
			/*71*/	"Brick Break",
			/*72*/	"Brine",
			/*73*/	"Brutal Swing",
			/*74*/	"Bubble Beam",
			/*75*/	"Bubble",
			/*76*/	"Bug Bite",
			/*77*/	"Bug Buzz",
			/*78*/	"Bulk Up",
			/*79*/	"Bulldoze",
			/*80*/	"Bullet Punch",
			/*81*/	"Bullet Seed",
			/*82*/	"Burn Up",
			/*83*/	"Calm Mind",
			/*84*/	"Camouflage",
			/*85*/	"Captivate",
			/*86*/	"Catastropika",
			/*87*/	"Celebrate",
			/*88*/	"Charge Beam",
			/*89*/	"Charge",
			/*90*/	"Charm",
			/*91*/	"Chatter",
			/*92*/	"Chip Away",
			/*93*/	"Circle Throw",
			/*94*/	"Clamp",
			/*95*/	"Clanging Scales",
			/*96*/	"Clear Smog",
			/*97*/	"Close Combat",
			/*98*/	"Coil",
			/*99*/	"Comet Punch",
			/*100*/	"Confide",
			/*101*/	"Confuse Ray",
			/*102*/	"Confusion",
			/*103*/	"Constrict",
			/*104*/	"Continental Crush",
			/*105*/	"Continental Crush",
			/*106*/	"Conversion 2",
			/*107*/	"Conversion",
			/*108*/	"Copycat",
			/*109*/	"Core Enforcer",
			/*110*/	"Corkscrew Crash",
			/*111*/	"Corkscrew Crash",
			/*112*/	"Cosmic Power",
			/*113*/	"Cotton Guard",
			/*114*/	"Cotton Spore",
			/*115*/	"Counter",
			/*116*/	"Covet",
			/*117*/	"Crabhammer",
			/*118*/	"Crafty Shield",
			/*119*/	"Cross Chop",
			/*120*/	"Cross Poison",
			/*121*/	"Crunch",
			/*122*/	"Crush Claw",
			/*123*/	"Crush Grip",
			/*124*/	"Curse",
			/*125*/	"Cut",
			/*126*/	"Dark Pulse",
			/*127*/	"Dark Void",
			/*128*/	"Darkest Lariat",
			/*129*/	"Dazzling Gleam",
			/*130*/	"Defend Order",
			/*131*/	"Defense Curl",
			/*132*/	"Defog",
			/*133*/	"Destiny Bond",
			/*134*/	"Detect",
			/*135*/	"Devastating Drake",
			/*136*/	"Devastating Drake",
			/*137*/	"Diamond Storm",
			/*138*/	"Dig",
			/*139*/	"Disable",
			/*140*/	"Disarming Voice",
			/*141*/	"Discharge",
			/*142*/	"Dive",
			/*143*/	"Dizzy Punch",
			/*144*/	"Doom Desire",
			/*145*/	"Double Hit",
			/*146*/	"Double Kick",
			/*147*/	"Double Slap",
			/*148*/	"Double Team",
			/*149*/	"Double-Edge",
			/*150*/	"Draco Meteor",
			/*151*/	"Dragon Ascent",
			/*152*/	"Dragon Breath",
			/*153*/	"Dragon Claw",
			/*154*/	"Dragon Dance",
			/*155*/	"Dragon Hammer",
			/*156*/	"Dragon Pulse",
			/*157*/	"Dragon Rage",
			/*158*/	"Dragon Rush",
			/*159*/	"Dragon Tail",
			/*160*/	"Drain Punch",
			/*161*/	"Draining Kiss",
			/*162*/	"Dream Eater",
			/*163*/	"Drill Peck",
			/*164*/	"Drill Run",
			/*165*/	"Dual Chop",
			/*166*/	"Dynamic Punch",
			/*167*/	"Earth Power",
			/*168*/	"Earthquake",
			/*169*/	"Echoed Voice",
			/*170*/	"Eerie Impulse",
			/*171*/	"Egg Bomb",
			/*172*/	"Electric Terrain",
			/*173*/	"Electrify",
			/*174*/	"Electro Ball",
			/*175*/	"Electroweb",
			/*176*/	"Embargo",
			/*177*/	"Ember",
			/*178*/	"Encore",
			/*179*/	"Endeavor",
			/*180*/	"Endure",
			/*181*/	"Energy Ball",
			/*182*/	"Entrainment",
			/*183*/	"Eruption",
			/*184*/	"Explosion",
			/*185*/	"Extrasensory",
			/*186*/	"Extreme Evoboost",
			/*187*/	"Extreme Speed",
			/*188*/	"Facade",
			/*189*/	"Fairy Lock",
			/*190*/	"Fairy Wind",
			/*191*/	"Fake Out",
			/*192*/	"Fake Tears",
			/*193*/	"False Swipe",
			/*194*/	"Feather Dance",
			/*195*/	"Feint Attack",
			/*196*/	"Feint",
			/*197*/	"Fell Stinger",
			/*198*/	"Fiery Dance",
			/*199*/	"Final Gambit",
			/*200*/	"Fire Blast",
			/*201*/	"Fire Fang",
			/*202*/	"Fire Lash",
			/*203*/	"Fire Pledge",
			/*204*/	"Fire Punch",
			/*205*/	"Fire Spin",
			/*206*/	"First Impression",
			/*207*/	"Fissure",
			/*208*/	"Flail",
			/*209*/	"Flame Burst",
			/*210*/	"Flame Charge",
			/*211*/	"Flame Wheel",
			/*212*/	"Flamethrower",
			/*213*/	"Flare Blitz",
			/*214*/	"Flash Cannon",
			/*215*/	"Flash",
			/*216*/	"Flatter",
			/*217*/	"Fleur Cannon",
			/*218*/	"Fling",
			/*219*/	"Floral Healing",
			/*220*/	"Flower Shield",
			/*221*/	"Fly",
			/*222*/	"Flying Press",
			/*223*/	"Focus Blast",
			/*224*/	"Focus Energy",
			/*225*/	"Focus Punch",
			/*226*/	"Follow Me",
			/*227*/	"Force Palm",
			/*228*/	"Foresight",
			/*229*/	"Forest's Curse",
			/*230*/	"Foul Play",
			/*231*/	"Freeze Shock",
			/*232*/	"Freeze-Dry",
			/*233*/	"Frenzy Plant",
			/*234*/	"Frost Breath",
			/*235*/	"Frustration",
			/*236*/	"Fury Attack",
			/*237*/	"Fury Cutter",
			/*238*/	"Fury Swipes",
			/*239*/	"Fusion Bolt",
			/*240*/	"Fusion Flare",
			/*241*/	"Future Sight",
			/*242*/	"Gastro Acid",
			/*243*/	"Gear Grind",
			/*244*/	"Gear Up",
			/*245*/	"Genesis Supernova",
			/*246*/	"Geomancy",
			/*247*/	"Giga Drain",
			/*248*/	"Giga Impact",
			/*249*/	"Gigavolt Havoc",
			/*250*/	"Gigavolt Havoc",
			/*251*/	"Glaciate",
			/*252*/	"Glare",
			/*253*/	"Grass Knot",
			/*254*/	"Grass Pledge",
			/*255*/	"Grass Whistle",
			/*256*/	"Grassy Terrain",
			/*257*/	"Gravity",
			/*258*/	"Growl",
			/*259*/	"Growth",
			/*260*/	"Grudge",
			/*261*/	"Guard Split",
			/*262*/	"Guard Swap",
			/*263*/	"Guardian of Alola",
			/*264*/	"Guillotine",
			/*265*/	"Gunk Shot",
			/*266*/	"Gust",
			/*267*/	"Gyro Ball",
			/*268*/	"Hail",
			/*269*/	"Hammer Arm",
			/*270*/	"Happy Hour",
			/*271*/	"Harden",
			/*272*/	"Haze",
			/*273*/	"Head Charge",
			/*274*/	"Head Smash",
			/*275*/	"Headbutt",
			/*276*/	"Heal Bell",
			/*277*/	"Heal Block",
			/*278*/	"Heal Order",
			/*279*/	"Heal Pulse",
			/*280*/	"Healing Wish",
			/*281*/	"Heart Stamp",
			/*282*/	"Heart Swap",
			/*283*/	"Heat Crash",
			/*284*/	"Heat Wave",
			/*285*/	"Heavy Slam",
			/*286*/	"Helping Hand",
			/*287*/	"Hex",
			/*288*/	"Hidden Power",
			/*289*/	"High Horsepower",
			/*290*/	"High Jump Kick",
			/*291*/	"Hold Back",
			/*292*/	"Hold Hands",
			/*293*/	"Hone Claws",
			/*294*/	"Horn Attack",
			/*295*/	"Horn Drill",
			/*296*/	"Horn Leech",
			/*297*/	"Howl",
			/*298*/	"Hurricane",
			/*299*/	"Hydro Cannon",
			/*300*/	"Hydro Pump",
			/*301*/	"Hydro Vortex",
			/*302*/	"Hydro Vortex",
			/*303*/	"Hyper Beam",
			/*304*/	"Hyper Fang",
			/*305*/	"Hyper Voice",
			/*306*/	"Hyperspace Fury",
			/*307*/	"Hyperspace Hole",
			/*308*/	"Hypnosis",
			/*309*/	"Ice Ball",
			/*310*/	"Ice Beam",
			/*311*/	"Ice Burn",
			/*312*/	"Ice Fang",
			/*313*/	"Ice Hammer",
			/*314*/	"Ice Punch",
			/*315*/	"Ice Shard",
			/*316*/	"Icicle Crash",
			/*317*/	"Icicle Spear",
			/*318*/	"Icy Wind",
			/*319*/	"Imprison",
			/*320*/	"Incinerate",
			/*321*/	"Inferno Overdrive",
			/*322*/	"Inferno Overdrive",
			/*323*/	"Inferno",
			/*324*/	"Infestation",
			/*325*/	"Ingrain",
			/*326*/	"Instruct",
			/*327*/	"Ion Deluge",
			/*328*/	"Iron Defense",
			/*329*/	"Iron Head",
			/*330*/	"Iron Tail",
			/*331*/	"Judgment",
			/*332*/	"Jump Kick",
			/*333*/	"Karate Chop",
			/*334*/	"Kinesis",
			/*335*/	"King's Shield",
			/*336*/	"Knock Off",
			/*337*/	"Land's Wrath",
			/*338*/	"Laser Focus",
			/*339*/	"Last Resort",
			/*340*/	"Lava Plume",
			/*341*/	"Leaf Blade",
			/*342*/	"Leaf Storm",
			/*343*/	"Leaf Tornado",
			/*344*/	"Leafage",
			/*345*/	"Leech Life",
			/*346*/	"Leech Seed",
			/*347*/	"Leer",
			/*348*/	"Lick",
			/*349*/	"Light of Ruin",
			/*350*/	"Light Screen",
			/*351*/	"Liquidation",
			/*352*/	"Lock-On",
			/*353*/	"Lovely Kiss",
			/*354*/	"Low Kick",
			/*355*/	"Low Sweep",
			/*356*/	"Lucky Chant",
			/*357*/	"Lunar Dance",
			/*358*/	"Lunge",
			/*359*/	"Luster Purge",
			/*360*/	"Mach Punch",
			/*361*/	"Magic Coat",
			/*362*/	"Magic Room",
			/*363*/	"Magical Leaf",
			/*364*/	"Magma Storm",
			/*365*/	"Magnet Bomb",
			/*366*/	"Magnet Rise",
			/*367*/	"Magnetic Flux",
			/*368*/	"Magnitude",
			/*369*/	"Malicious Moonsault",
			/*370*/	"Mat Block",
			/*371*/	"Me First",
			/*372*/	"Mean Look",
			/*373*/	"Meditate",
			/*374*/	"Mega Drain",
			/*375*/	"Mega Kick",
			/*376*/	"Mega Punch",
			/*377*/	"Megahorn",
			/*378*/	"Memento",
			/*379*/	"Metal Burst",
			/*380*/	"Metal Claw",
			/*381*/	"Metal Sound",
			/*382*/	"Meteor Mash",
			/*383*/	"Metronome",
			/*384*/	"Milk Drink",
			/*385*/	"Mimic",
			/*386*/	"Mind Reader",
			/*387*/	"Minimize",
			/*388*/	"Miracle Eye",
			/*389*/	"Mirror Coat",
			/*390*/	"Mirror Move",
			/*391*/	"Mirror Shot",
			/*392*/	"Mist Ball",
			/*393*/	"Mist",
			/*394*/	"Misty Terrain",
			/*395*/	"Moonblast",
			/*396*/	"Moongeist Beam",
			/*397*/	"Moonlight",
			/*398*/	"Morning Sun",
			/*399*/	"Mud Bomb",
			/*400*/	"Mud Shot",
			/*401*/	"Mud Sport",
			/*402*/	"Muddy Water",
			/*403*/	"Mud-Slap",
			/*404*/	"Multi-Attack",
			/*405*/	"Mystical Fire",
			/*406*/	"Nasty Plot",
			/*407*/	"Natural Gift",
			/*408*/	"Nature Power",
			/*409*/	"Nature's Madness",
			/*410*/	"Needle Arm",
			/*411*/	"Never-Ending Nightmare",
			/*412*/	"Never-Ending Nightmare",
			/*413*/	"Night Daze",
			/*414*/	"Night Shade",
			/*415*/	"Night Slash",
			/*416*/	"Nightmare",
			/*417*/	"Noble Roar",
			/*418*/	"Nuzzle",
			/*419*/	"Oblivion Wing",
			/*420*/	"Oceanic Operetta",
			/*421*/	"Octazooka",
			/*422*/	"Odor Sleuth",
			/*423*/	"Ominous Wind",
			/*424*/	"Origin Pulse",
			/*425*/	"Outrage",
			/*426*/	"Overheat",
			/*427*/	"Pain Split",
			/*428*/	"Parabolic Charge",
			/*429*/	"Parting Shot",
			/*430*/	"Pay Day",
			/*431*/	"Payback",
			/*432*/	"Peck",
			/*433*/	"Perish Song",
			/*434*/	"Petal Blizzard",
			/*435*/	"Petal Dance",
			/*436*/	"Phantom Force",
			/*437*/	"Pin Missile",
			/*438*/	"Play Nice",
			/*439*/	"Play Rough",
			/*440*/	"Pluck",
			/*441*/	"Poison Fang",
			/*442*/	"Poison Gas",
			/*443*/	"Poison Jab",
			/*444*/	"Poison Powder",
			/*445*/	"Poison Sting",
			/*446*/	"Poison Tail",
			/*447*/	"Pollen Puff",
			/*448*/	"Pound",
			/*449*/	"Powder Snow",
			/*450*/	"Powder",
			/*451*/	"Power Gem",
			/*452*/	"Power Split",
			/*453*/	"Power Swap",
			/*454*/	"Power Trick",
			/*455*/	"Power Trip",
			/*456*/	"Power Whip",
			/*457*/	"Power-Up Punch",
			/*458*/	"Precipice Blades",
			/*459*/	"Present",
			/*460*/	"Prismatic Laser",
			/*461*/	"Protect",
			/*462*/	"Psybeam",
			/*463*/	"Psych Up",
			/*464*/	"Psychic Fangs",
			/*465*/	"Psychic Terrain",
			/*466*/	"Psychic",
			/*467*/	"Psycho Boost",
			/*468*/	"Psycho Cut",
			/*469*/	"Psycho Shift",
			/*470*/	"Psyshock",
			/*471*/	"Psystrike",
			/*472*/	"Psywave",
			/*473*/	"Pulverizing Pancake",
			/*474*/	"Punishment",
			/*475*/	"Purify",
			/*476*/	"Pursuit",
			/*477*/	"Quash",
			/*478*/	"Quick Attack",
			/*479*/	"Quick Guard",
			/*480*/	"Quiver Dance",
			/*481*/	"Rage Powder",
			/*482*/	"Rage",
			/*483*/	"Rain Dance",
			/*484*/	"Rapid Spin",
			/*485*/	"Razor Leaf",
			/*486*/	"Razor Shell",
			/*487*/	"Razor Wind",
			/*488*/	"Recover",
			/*489*/	"Recycle",
			/*490*/	"Reflect Type",
			/*491*/	"Reflect",
			/*492*/	"Refresh",
			/*493*/	"Relic Song",
			/*494*/	"Rest",
			/*495*/	"Retaliate",
			/*496*/	"Return",
			/*497*/	"Revelation Dance",
			/*498*/	"Revenge",
			/*499*/	"Reversal",
			/*500*/	"Roar of Time",
			/*501*/	"Roar",
			/*502*/	"Rock Blast",
			/*503*/	"Rock Climb",
			/*504*/	"Rock Polish",
			/*505*/	"Rock Slide",
			/*506*/	"Rock Smash",
			/*507*/	"Rock Throw",
			/*508*/	"Rock Tomb",
			/*509*/	"Rock Wrecker",
			/*510*/	"Role Play",
			/*511*/	"Rolling Kick",
			/*512*/	"Rollout",
			/*513*/	"Roost",
			/*514*/	"Rototiller",
			/*515*/	"Round",
			/*516*/	"Sacred Fire",
			/*517*/	"Sacred Sword",
			/*518*/	"Safeguard",
			/*519*/	"Sand Attack",
			/*520*/	"Sand Tomb",
			/*521*/	"Sandstorm",
			/*522*/	"Savage Spin-Out",
			/*523*/	"Savage Spin-Out",
			/*524*/	"Scald",
			/*525*/	"Scary Face",
			/*526*/	"Scratch",
			/*527*/	"Screech",
			/*528*/	"Searing Shot",
			/*529*/	"Secret Power",
			/*530*/	"Secret Sword",
			/*531*/	"Seed Bomb",
			/*532*/	"Seed Flare",
			/*533*/	"Seismic Toss",
			/*534*/	"Self-Destruct",
			/*535*/	"Shadow Ball",
			/*536*/	"Shadow Bone",
			/*537*/	"Shadow Claw",
			/*538*/	"Shadow Force",
			/*539*/	"Shadow Punch",
			/*540*/	"Shadow Sneak",
			/*541*/	"Sharpen",
			/*542*/	"Shattered Psyche",
			/*543*/	"Shattered Psyche",
			/*544*/	"Sheer Cold",
			/*545*/	"Shell Smash",
			/*546*/	"Shell Trap",
			/*547*/	"Shift Gear",
			/*548*/	"Shock Wave",
			/*549*/	"Shore Up",
			/*550*/	"Signal Beam",
			/*551*/	"Silver Wind",
			/*552*/	"Simple Beam",
			/*553*/	"Sing",
			/*554*/	"Sinister Arrow Raid",
			/*555*/	"Sketch",
			/*556*/	"Skill Swap",
			/*557*/	"Skull Bash",
			/*558*/	"Sky Attack",
			/*559*/	"Sky Drop",
			/*560*/	"Sky Uppercut",
			/*561*/	"Slack Off",
			/*562*/	"Slam",
			/*563*/	"Slash",
			/*564*/	"Sleep Powder",
			/*565*/	"Sleep Talk",
			/*566*/	"Sludge Bomb",
			/*567*/	"Sludge Wave",
			/*568*/	"Sludge",
			/*569*/	"Smack Down",
			/*570*/	"Smart Strike",
			/*571*/	"Smelling Salts",
			/*572*/	"Smog",
			/*573*/	"Smokescreen",
			/*574*/	"Snarl",
			/*575*/	"Snatch",
			/*576*/	"Snore",
			/*577*/	"Soak",
			/*578*/	"Soft-Boiled",
			/*579*/	"Solar Beam",
			/*580*/	"Solar Blade",
			/*581*/	"Sonic Boom",
			/*582*/	"Soul-Stealing 7-Star Strike",
			/*583*/	"Spacial Rend",
			/*584*/	"Spark",
			/*585*/	"Sparkling Aria",
			/*586*/	"Spectral Thief",
			/*587*/	"Speed Swap",
			/*588*/	"Spider Web",
			/*589*/	"Spike Cannon",
			/*590*/	"Spikes",
			/*591*/	"Spiky Shield",
			/*592*/	"Spirit Shackle",
			/*593*/	"Spit Up",
			/*594*/	"Spite",
			/*595*/	"Splash",
			/*596*/	"Spore",
			/*597*/	"Spotlight",
			/*598*/	"Stealth Rock",
			/*599*/	"Steam Eruption",
			/*600*/	"Steamroller",
			/*601*/	"Steel Wing",
			/*602*/	"Sticky Web",
			/*603*/	"Stockpile",
			/*604*/	"Stoked Sparksurfer",
			/*605*/	"Stomp",
			/*606*/	"Stomping Tantrum",
			/*607*/	"Stone Edge",
			/*608*/	"Stored Power",
			/*609*/	"Storm Throw",
			/*610*/	"Strength Sap",
			/*611*/	"Strength",
			/*612*/	"String Shot",
			/*613*/	"Struggle Bug",
			/*614*/	"Struggle",
			/*615*/	"Stun Spore",
			/*616*/	"Submission",
			/*617*/	"Substitute",
			/*618*/	"Subzero Slammer",
			/*619*/	"Subzero Slammer",
			/*620*/	"Sucker Punch",
			/*621*/	"Sunny Day",
			/*622*/	"Sunsteel Strike",
			/*623*/	"Super Fang",
			/*624*/	"Superpower",
			/*625*/	"Supersonic Skystrike",
			/*626*/	"Supersonic Skystrike",
			/*627*/	"Supersonic",
			/*628*/	"Surf",
			/*629*/	"Swagger",
			/*630*/	"Swallow",
			/*631*/	"Sweet Kiss",
			/*632*/	"Sweet Scent",
			/*633*/	"Swift",
			/*634*/	"Switcheroo",
			/*635*/	"Swords Dance",
			/*636*/	"Synchronoise",
			/*637*/	"Synthesis",
			/*638*/	"Tackle",
			/*639*/	"Tail Glow",
			/*640*/	"Tail Slap",
			/*641*/	"Tail Whip",
			/*642*/	"Tailwind",
			/*643*/	"Take Down",
			/*644*/	"Taunt",
			/*645*/	"Tearful Look",
			/*646*/	"Techno Blast",
			/*647*/	"Tectonic Rage",
			/*648*/	"Tectonic Rage",
			/*649*/	"Teeter Dance",
			/*650*/	"Telekinesis",
			/*651*/	"Teleport",
			/*652*/	"Thief",
			/*653*/	"Thousand Arrows",
			/*654*/	"Thousand Waves",
			/*655*/	"Thrash",
			/*656*/	"Throat Chop",
			/*657*/	"Thunder Fang",
			/*658*/	"Thunder Punch",
			/*659*/	"Thunder Shock",
			/*660*/	"Thunder Wave",
			/*661*/	"Thunder",
			/*662*/	"Thunderbolt",
			/*663*/	"Tickle",
			/*664*/	"Topsy-Turvy",
			/*665*/	"Torment",
			/*666*/	"Toxic Spikes",
			/*667*/	"Toxic Thread",
			/*668*/	"Toxic",
			/*669*/	"Transform",
			/*670*/	"Tri Attack",
			/*671*/	"Trick Room",
			/*672*/	"Trick",
			/*673*/	"Trick-or-Treat",
			/*674*/	"Triple Kick",
			/*675*/	"Trop Kick",
			/*676*/	"Trump Card",
			/*677*/	"Twineedle",
			/*678*/	"Twinkle Tackle",
			/*679*/	"Twinkle Tackle",
			/*680*/	"Twister",
			/*681*/	"Uproar",
			/*682*/	"U-turn",
			/*683*/	"Vacuum Wave",
			/*684*/	"V-create",
			/*685*/	"Venom Drench",
			/*686*/	"Venoshock",
			/*687*/	"Vice Grip",
			/*688*/	"Vine Whip",
			/*689*/	"Vital Throw",
			/*690*/	"Volt Switch",
			/*691*/	"Volt Tackle",
			/*692*/	"Wake-Up Slap",
			/*693*/	"Water Gun",
			/*694*/	"Water Pledge",
			/*695*/	"Water Pulse",
			/*696*/	"Water Shuriken",
			/*697*/	"Water Sport",
			/*698*/	"Water Spout",
			/*699*/	"Waterfall",
			/*700*/	"Weather Ball",
			/*701*/	"Whirlpool",
			/*702*/	"Whirlwind",
			/*703*/	"Wide Guard",
			/*704*/	"Wild Charge",
			/*705*/	"Will-O-Wisp",
			/*706*/	"Wing Attack",
			/*707*/	"Wish",
			/*708*/	"Withdraw",
			/*709*/	"Wonder Room",
			/*710*/	"Wood Hammer",
			/*711*/	"Work Up",
			/*712*/	"Worry Seed",
			/*713*/	"Wrap",
			/*714*/	"Wring Out",
			/*715*/	"X-Scissor",
			/*716*/	"Yawn",
			/*717*/	"Zap Cannon",
			/*718*/	"Zen Headbutt",
			/*719*/	"Zing Zap"
		};
	
	public static String[] moveClasses =
		{
			"None",
			"TenMillionVoltThunderbolt",
			"Absorb",
			"Accelerock",
			"Acid",
			"AcidArmor",
			"AcidDownpourP",
			"AcidDownpourS",
			"AcidSpray",
			"Acrobatics",
			"Acupressure",
			"AerialAce",
			"Aeroblast",
			"AfterYou",
			"Agility",
			"AirCutter",
			"AirSlash",
			"AllOutPummelingP",
			"AllOutPummelingS",
			"AllySwitch",
			"Amnesia",
			"AnchorShot",
			"AncientPower",
			"AquaJet",
			"AquaRing",
			"AquaTail",
			"ArmThrust",
			"Aromatherapy",
			"AromaticMist",
			"Assist",
			"Assurance",
			"Astonish",
			"AttackOrder",
			"Attract",
			"AuraSphere",
			"AuroraBeam",
			"AuroraVeil",
			"Autotomize",
			"Avalanche",
			"BabyDollEyes",
			"BanefulBunker",
			"Barrage",
			"Barrier",
			"BatonPass",
			"BeakBlast",
			"BeatUp",
			"Belch",
			"BellyDrum",
			"Bestow",
			"Bide",
			"Bind",
			"Bite",
			"BlackHoleEclipseP",
			"BlackHoleEclipseS",
			"BlastBurn",
			"BlazeKick",
			"Blizzard",
			"Block",
			"BloomDoomP",
			"BloomDoomS",
			"BlueFlare",
			"BodySlam",
			"BoltStrike",
			"BoneClub",
			"BoneRush",
			"Bonemerang",
			"Boomburst",
			"Bounce",
			"BraveBird",
			"BreakneckBlitzP",
			"BreakneckBlitzS",
			"BrickBreak",
			"Brine",
			"BrutalSwing",
			"BubbleBeam",
			"Bubble",
			"BugBite",
			"BugBuzz",
			"BulkUp",
			"Bulldoze",
			"BulletPunch",
			"BulletSeed",
			"BurnUp",
			"CalmMind",
			"Camouflage",
			"Captivate",
			"Catastropika",
			"Celebrate",
			"ChargeBeam",
			"Charge",
			"Charm",
			"Chatter",
			"ChipAway",
			"CircleThrow",
			"Clamp",
			"ClangingScales",
			"ClearSmog",
			"CloseCombat",
			"Coil",
			"CometPunch",
			"Confide",
			"ConfuseRay",
			"Confusion",
			"Constrict",
			"ContinentalCrushP",
			"ContinentalCrushS",
			"Conversion2",
			"Conversion",
			"Copycat",
			"CoreEnforcer",
			"CorkscrewCrashP",
			"CorkscrewCrashS",
			"CosmicPower",
			"CottonGuard",
			"CottonSpore",
			"Counter",
			"Covet",
			"Crabhammer",
			"CraftyShield",
			"CrossChop",
			"CrossPoison",
			"Crunch",
			"CrushClaw",
			"CrushGrip",
			"Curse",
			"Cut",
			"DarkPulse",
			"DarkVoid",
			"DarkestLariat",
			"DazzlingGleam",
			"DefendOrder",
			"DefenseCurl",
			"Defog",
			"DestinyBond",
			"Detect",
			"DevastatingDrakeP",
			"DevastatingDrakeS",
			"DiamondStorm",
			"Dig",
			"Disable",
			"DisarmingVoice",
			"Discharge",
			"Dive",
			"DizzyPunch",
			"DoomDesire",
			"DoubleHit",
			"DoubleKick",
			"DoubleSlap",
			"DoubleTeam",
			"DoubleEdge",
			"DracoMeteor",
			"DragonAscent",
			"DragonBreath",
			"DragonClaw",
			"DragonDance",
			"DragonHammer",
			"DragonPulse",
			"DragonRage",
			"DragonRush",
			"DragonTail",
			"DrainPunch",
			"DrainingKiss",
			"DreamEater",
			"DrillPeck",
			"DrillRun",
			"DualChop",
			"DynamicPunch",
			"EarthPower",
			"Earthquake",
			"EchoedVoice",
			"EerieImpulse",
			"EggBomb",
			"ElectricTerrain",
			"Electrify",
			"ElectroBall",
			"Electroweb",
			"Embargo",
			"Ember",
			"Encore",
			"Endeavor",
			"Endure",
			"EnergyBall",
			"Entrainment",
			"Eruption",
			"Explosion",
			"Extrasensory",
			"ExtremeEvoboost",
			"ExtremeSpeed",
			"Facade",
			"FairyLock",
			"FairyWind",
			"FakeOut",
			"FakeTears",
			"FalseSwipe",
			"FeatherDance",
			"FeintAttack",
			"Feint",
			"FellStinger",
			"FieryDance",
			"FinalGambit",
			"FireBlast",
			"FireFang",
			"FireLash",
			"FirePledge",
			"FirePunch",
			"FireSpin",
			"FirstImpression",
			"Fissure",
			"Flail",
			"FlameBurst",
			"FlameCharge",
			"FlameWheel",
			"Flamethrower",
			"FlareBlitz",
			"FlashCannon",
			"Flash",
			"Flatter",
			"FleurCannon",
			"Fling",
			"FloralHealing",
			"FlowerShield",
			"Fly",
			"FlyingPress",
			"FocusBlast",
			"FocusEnergy",
			"FocusPunch",
			"FollowMe",
			"ForcePalm",
			"Foresight",
			"ForestsCurse",
			"FoulPlay",
			"FreezeShock",
			"FreezeDry",
			"FrenzyPlant",
			"FrostBreath",
			"Frustration",
			"FuryAttack",
			"FuryCutter",
			"FurySwipes",
			"FusionBolt",
			"FusionFlare",
			"FutureSight",
			"GastroAcid",
			"GearGrind",
			"GearUp",
			"GenesisSupernova",
			"Geomancy",
			"GigaDrain",
			"GigaImpact",
			"GigavoltHavocP",
			"GigavoltHavocS",
			"Glaciate",
			"Glare",
			"GrassKnot",
			"GrassPledge",
			"GrassWhistle",
			"GrassyTerrain",
			"Gravity",
			"Growl",
			"Growth",
			"Grudge",
			"GuardSplit",
			"GuardSwap",
			"GuardianofAlola",
			"Guillotine",
			"GunkShot",
			"Gust",
			"GyroBall",
			"Hail",
			"HammerArm",
			"HappyHour",
			"Harden",
			"Haze",
			"HeadCharge",
			"HeadSmash",
			"Headbutt",
			"HealBell",
			"HealBlock",
			"HealOrder",
			"HealPulse",
			"HealingWish",
			"HeartStamp",
			"HeartSwap",
			"HeatCrash",
			"HeatWave",
			"HeavySlam",
			"HelpingHand",
			"Hex",
			"HiddenPower",
			"HighHorsepower",
			"HighJumpKick",
			"HoldBack",
			"HoldHands",
			"HoneClaws",
			"HornAttack",
			"HornDrill",
			"HornLeech",
			"Howl",
			"Hurricane",
			"HydroCannon",
			"HydroPump",
			"HydroVortexP",
			"HydroVortexS",
			"HyperBeam",
			"HyperFang",
			"HyperVoice",
			"HyperspaceFury",
			"HyperspaceHole",
			"Hypnosis",
			"IceBall",
			"IceBeam",
			"IceBurn",
			"IceFang",
			"IceHammer",
			"IcePunch",
			"IceShard",
			"IcicleCrash",
			"IcicleSpear",
			"IcyWind",
			"Imprison",
			"Incinerate",
			"InfernoOverdriveP",
			"InfernoOverdriveS",
			"Inferno",
			"Infestation",
			"Ingrain",
			"Instruct",
			"IonDeluge",
			"IronDefense",
			"IronHead",
			"IronTail",
			"Judgment",
			"JumpKick",
			"KarateChop",
			"Kinesis",
			"KingsShield",
			"KnockOff",
			"LandsWrath",
			"LaserFocus",
			"LastResort",
			"LavaPlume",
			"LeafBlade",
			"LeafStorm",
			"LeafTornado",
			"Leafage",
			"LeechLife",
			"LeechSeed",
			"Leer",
			"Lick",
			"LightofRuin",
			"LightScreen",
			"Liquidation",
			"LockOn",
			"LovelyKiss",
			"LowKick",
			"LowSweep",
			"LuckyChant",
			"LunarDance",
			"Lunge",
			"LusterPurge",
			"MachPunch",
			"MagicCoat",
			"MagicRoom",
			"MagicalLeaf",
			"MagmaStorm",
			"MagnetBomb",
			"MagnetRise",
			"MagneticFlux",
			"Magnitude",
			"MaliciousMoonsault",
			"MatBlock",
			"MeFirst",
			"MeanLook",
			"Meditate",
			"MegaDrain",
			"MegaKick",
			"MegaPunch",
			"Megahorn",
			"Memento",
			"MetalBurst",
			"MetalClaw",
			"MetalSound",
			"MeteorMash",
			"Metronome",
			"MilkDrink",
			"Mimic",
			"MindReader",
			"Minimize",
			"MiracleEye",
			"MirrorCoat",
			"MirrorMove",
			"MirrorShot",
			"MistBall",
			"Mist",
			"MistyTerrain",
			"Moonblast",
			"MoongeistBeam",
			"Moonlight",
			"MorningSun",
			"MudBomb",
			"MudShot",
			"MudSport",
			"MuddyWater",
			"MudSlap",
			"MultiAttack",
			"MysticalFire",
			"NastyPlot",
			"NaturalGift",
			"NaturePower",
			"NaturesMadness",
			"NeedleArm",
			"NeverEndingNightmareP",
			"NeverEndingNightmareS",
			"NightDaze",
			"NightShade",
			"NightSlash",
			"Nightmare",
			"NobleRoar",
			"Nuzzle",
			"OblivionWing",
			"OceanicOperetta",
			"Octazooka",
			"OdorSleuth",
			"OminousWind",
			"OriginPulse",
			"Outrage",
			"Overheat",
			"PainSplit",
			"ParabolicCharge",
			"PartingShot",
			"PayDay",
			"Payback",
			"Peck",
			"PerishSong",
			"PetalBlizzard",
			"PetalDance",
			"PhantomForce",
			"PinMissile",
			"PlayNice",
			"PlayRough",
			"Pluck",
			"PoisonFang",
			"PoisonGas",
			"PoisonJab",
			"PoisonPowder",
			"PoisonSting",
			"PoisonTail",
			"PollenPuff",
			"Pound",
			"PowderSnow",
			"Powder",
			"PowerGem",
			"PowerSplit",
			"PowerSwap",
			"PowerTrick",
			"PowerTrip",
			"PowerWhip",
			"PowerUpPunch",
			"PrecipiceBlades",
			"Present",
			"PrismaticLaser",
			"Protect",
			"Psybeam",
			"PsychUp",
			"PsychicFangs",
			"PsychicTerrain",
			"Psychic",
			"PsychoBoost",
			"PsychoCut",
			"PsychoShift",
			"Psyshock",
			"Psystrike",
			"Psywave",
			"PulverizingPancake",
			"Punishment",
			"Purify",
			"Pursuit",
			"Quash",
			"QuickAttack",
			"QuickGuard",
			"QuiverDance",
			"RagePowder",
			"Rage",
			"RainDance",
			"RapidSpin",
			"RazorLeaf",
			"RazorShell",
			"RazorWind",
			"Recover",
			"Recycle",
			"ReflectType",
			"Reflect",
			"Refresh",
			"RelicSong",
			"Rest",
			"Retaliate",
			"Return",
			"RevelationDance",
			"Revenge",
			"Reversal",
			"RoarofTime",
			"Roar",
			"RockBlast",
			"RockClimb",
			"RockPolish",
			"RockSlide",
			"RockSmash",
			"RockThrow",
			"RockTomb",
			"RockWrecker",
			"RolePlay",
			"RollingKick",
			"Rollout",
			"Roost",
			"Rototiller",
			"Round",
			"SacredFire",
			"SacredSword",
			"Safeguard",
			"SandAttack",
			"SandTomb",
			"Sandstorm",
			"SavageSpinOutP",
			"SavageSpinOutS",
			"Scald",
			"ScaryFace",
			"Scratch",
			"Screech",
			"SearingShot",
			"SecretPower",
			"SecretSword",
			"SeedBomb",
			"SeedFlare",
			"SeismicToss",
			"SelfDestruct",
			"ShadowBall",
			"ShadowBone",
			"ShadowClaw",
			"ShadowForce",
			"ShadowPunch",
			"ShadowSneak",
			"Sharpen",
			"ShatteredPsycheP",
			"ShatteredPsycheS",
			"SheerCold",
			"ShellSmash",
			"ShellTrap",
			"ShiftGear",
			"ShockWave",
			"ShoreUp",
			"SignalBeam",
			"SilverWind",
			"SimpleBeam",
			"Sing",
			"SinisterArrowRaid",
			"Sketch",
			"SkillSwap",
			"SkullBash",
			"SkyAttack",
			"SkyDrop",
			"SkyUppercut",
			"SlackOff",
			"Slam",
			"Slash",
			"SleepPowder",
			"SleepTalk",
			"SludgeBomb",
			"SludgeWave",
			"Sludge",
			"SmackDown",
			"SmartStrike",
			"SmellingSalts",
			"Smog",
			"Smokescreen",
			"Snarl",
			"Snatch",
			"Snore",
			"Soak",
			"SoftBoiled",
			"SolarBeam",
			"SolarBlade",
			"SonicBoom",
			"SoulStealing7StarStrike",
			"SpacialRend",
			"Spark",
			"SparklingAria",
			"SpectralThief",
			"SpeedSwap",
			"SpiderWeb",
			"SpikeCannon",
			"Spikes",
			"SpikyShield",
			"SpiritShackle",
			"SpitUp",
			"Spite",
			"Splash",
			"Spore",
			"Spotlight",
			"StealthRock",
			"SteamEruption",
			"Steamroller",
			"SteelWing",
			"StickyWeb",
			"Stockpile",
			"StokedSparksurfer",
			"Stomp",
			"StompingTantrum",
			"StoneEdge",
			"StoredPower",
			"StormThrow",
			"StrengthSap",
			"Strength",
			"StringShot",
			"StruggleBug",
			"Struggle",
			"StunSpore",
			"Submission",
			"Substitute",
			"SubzeroSlammerP",
			"SubzeroSlammerS",
			"SuckerPunch",
			"SunnyDay",
			"SunsteelStrike",
			"SuperFang",
			"Superpower",
			"SupersonicSkystrikeP",
			"SupersonicSkystrikeS",
			"Supersonic",
			"Surf",
			"Swagger",
			"Swallow",
			"SweetKiss",
			"SweetScent",
			"Swift",
			"Switcheroo",
			"SwordsDance",
			"Synchronoise",
			"Synthesis",
			"Tackle",
			"TailGlow",
			"TailSlap",
			"TailWhip",
			"Tailwind",
			"TakeDown",
			"Taunt",
			"TearfulLook",
			"TechnoBlast",
			"TectonicRageP",
			"TectonicRageS",
			"TeeterDance",
			"Telekinesis",
			"Teleport",
			"Thief",
			"ThousandArrows",
			"ThousandWaves",
			"Thrash",
			"ThroatChop",
			"ThunderFang",
			"ThunderPunch",
			"ThunderShock",
			"ThunderWave",
			"Thunder",
			"Thunderbolt",
			"Tickle",
			"TopsyTurvy",
			"Torment",
			"ToxicSpikes",
			"ToxicThread",
			"Toxic",
			"Transform",
			"TriAttack",
			"TrickRoom",
			"Trick",
			"TrickorTreat",
			"TripleKick",
			"TropKick",
			"TrumpCard",
			"Twineedle",
			"TwinkleTackleP",
			"TwinkleTackleS",
			"Twister",
			"Uproar",
			"Uturn",
			"VacuumWave",
			"Vcreate",
			"VenomDrench",
			"Venoshock",
			"ViceGrip",
			"VineWhip",
			"VitalThrow",
			"VoltSwitch",
			"VoltTackle",
			"WakeUpSlap",
			"WaterGun",
			"WaterPledge",
			"WaterPulse",
			"WaterShuriken",
			"WaterSport",
			"WaterSpout",
			"Waterfall",
			"WeatherBall",
			"Whirlpool",
			"Whirlwind",
			"WideGuard",
			"WildCharge",
			"WillOWisp",
			"WingAttack",
			"Wish",
			"Withdraw",
			"WonderRoom",
			"WoodHammer",
			"WorkUp",
			"WorrySeed",
			"Wrap",
			"WringOut",
			"XScissor",
			"Yawn",
			"ZapCannon",
			"ZenHeadbutt",
			"ZingZap"
		};
}
